### ISSUE TITLE
Sentry.h file not found (manually link)

### ISSUE THREAD

**Issue by Hjord** [getsentry/sentry-react-native#1018]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.7.1

**`react-native` version:** 0.60.3

**Are you using Expo?**
- [ ]  Yes
- [X]  No

---
**I have following issue:**

I have an older app, in which I have updated to a newer version of react-native. Not using pod.
I've removed the old Sentry.

I've installed sentry from `@sentry/react-native`, and linked it manually, since I don' use pod.

The docs mention something with using the native SDK, so I've created a pod file with the only pod of `'Sentry', '=> 5.2'`, and installed it.

But the linked library is unable to find the pod. I've tried what other issues suggests. Using `<Sentry.h>`, `<Sentry/Sentry.h>` and "Sentry.h" for the import statement. But nothing seem to work.

I cant find any clear documentation for how I should be able to get it work. I guess I've missed a step or misunderstood something.
Any help will be appreciated.

**Actual result:**

Unable to build. `Sentry.h file not found` in `RNSentry.m`

**Expected result:**

Build with no problem.

**Comment by jennmueng** [comment]
@Hjord If you're using `0.60.3` can you enable auto linking? That should just solve the problem. But otherwise if you manually  link the library looks like you have to make sure that the pods get loaded **before** the linked library does.

I apologize, but I haven't had experience with using a single pod and manually linking a library before so I don't know how to help other than just letting you know to make sure that it gets loaded in the right order.

**Comment by Hjord** [comment]
@jennmueng 
Should have mentioned I already tried that.
If I try that this is added to AppDelegate.m

`#if __has_include(<React/RNSentry.h>)
#import <React/RNSentry.h> // This is used for versions of react >= 0.40
#else
#import "RNSentry.h" // This is used for versions of react < 0.40
#endif`

It cant find `RNSentry.h`, If I remove the check, since it's for < 0.40.0, I just get the same with file not found for. `React/RNSentry.h`

**Comment by jennmueng** [comment]
@Hjord Hmm is it possible for you to just use CocoaPods for `RNSentry`?

I'm sorry but this just looks like a specific configuration issue with your unique case and not an issue with the SDK.

**Comment by Hjord** [comment]
@jennmueng 
I don't see how it's a unique case. I don't think there is something wrong with the SDK, but the documentation.

The readme says install and link, for <= 0.60.x, which should just apply for me, right? But that doesn't work.
The install steps in the [docs](https://docs.sentry.io/platforms/react-native/#integrating-the-sdk) says to use link if < 0.60 and pod if >= 0.60. But that does not apply to me.

Is it not possible to use it in > 0.60, without using pods?

**Comment by jennmueng** [comment]
@Hjord This is because if you want to completely manually link the SDK without using cocoapods you will need to install the `sentry-cocoa` SDK yourself as the react native SDK depends on that. This error is occurring because on build time the `sentry-cocoa` SDK can't be found. If you just use cocoa pods to install the react-native SDK then the cocoa SDK will be automatically installed as a dependency by cocoapods.

The docs for <= 0.60 to install and link still depends on cocoapods.

**Comment by jennmueng** [comment]
@Hjord Hmm, when you install the Sentry cocoa SDK with cocoapods have you made sure that it is in the header search paths?

**Comment by Hjord** [comment]
@jennmueng 
I haven't tried installing the Cocoa SDK manually.
But yes, I've tried adding different paths to the header search paths, without success.

**Comment by jennmueng** [comment]
@Hjord So you're only using a single cocoa pod with `'Sentry', '=> 5.2'`, right? Have you followed the installation instructions for cocoapods into your Xcode project? Are you using the .xcworkspace or the .xcproject?

**Comment by Hjord** [comment]
@jennmueng 
Sorry mixed it up :) 
Yes i tried that. Both with workspace and project. In my code, `AppDelegate.m`, I could import `Sentry.h`, but it didn't work in `RNSentry.m`, which was under Libraries, after manually link.

**Comment by pinguo-zhouwei** [comment]
Encountered the same problem, is there a solution?

react-native: 0.59.9
sentry-react-native: 1.7.2

**Comment by marandaneto** [comment]
does that still happen using the latest Sentry RN SDK? I don't have any issues if using auto-linking or manual linking, although its the latest FB RN SDK as well
