### ISSUE TITLE
Question: is Sentry helpful for analyzing crashes in release builds without the sourcemap? 

### ISSUE THREAD

**Issue by rahamin1** [getsentry/sentry-react-native#1073]
I see several issues complaining that the sourcemap is included although it shouldn't (e.g. https://github.com/getsentry/sentry-react-native/issues/601).

Isn't the idea to add the sourcemap to the release build, in order to get meaningful info regarding crashes? 
Is Sentry helpful for analyzing crashes in release builds without the sourcemap?

**Comment by jennmueng** [comment]
Yes source maps are incredibly helpful in demangling minified code that's running in production. In the issue that you linked, the problem was the source map was included with the release bundle, as it shouldn't, and instead it should be uploaded to Sentry and not included with the build.

However, even without source maps you do get the full exception, along with all the context, tags, user info, etc surrounding it.
