### ISSUE TITLE
Fails to upload with organization slug (An organization slug is required (provide with --org)) v2.0.0

### ISSUE THREAD

**Issue by karlludwigweise** [getsentry/sentry-react-native#1173]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 2.0.0

**`react-native` version:** 0.63.3

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

---
**I have following issue:**

XCode files an error for the "Upload Debug Symbols to Sentry" build task

This is the error:
```
error: An organization slug is required (provide with --org)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
Continuing in background.
Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure
```

My sentry.properties
```
defaults.url=https://sentry.io/
defaults.org=***
defaults.project=***
auth.token=***
cli.executable=node_modules/@sentry/cli/bin/sentry-cli
```

**Steps to reproduce:**
- Make an XCode build

**Actual result:**

Build is successfaul, but task fails.

**Expected result:**

Task won't fail.

**Comment by jennmueng** [comment]
Hmm where do you have your `sentry.properties` file, it should be in `project_root/ios`.

**Comment by karlludwigweise** [comment]
That is exactly where it is. I used the sentry wizard to set this up months ago.
The problem occured after upgrading to v2.0.0

**Comment by jennmueng** [comment]
Can you paste the code you have for the failing build task?

**Comment by karlludwigweise** [comment]
This is it:

```
# Setup nvm and set node --start
[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"

if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
. "$HOME/.nvm/nvm.sh"
elif [[ -x "$(command -v brew)" && -s "$(brew --prefix nvm)/nvm.sh" ]]; then
. "$(brew --prefix nvm)/nvm.sh"
fi

[ -z "$NODE_BINARY" ] && export NODE_BINARY="node"

$NODE_BINARY ../node_modules/@sentry/cli/bin/sentry-cli upload-dsym
# --end

export SENTRY_PROPERTIES=sentry.properties
../node_modules/@sentry/cli/bin/sentry-cli upload-dsym
```

I am using nvm, that's the upper part for.

**Comment by jennmueng** [comment]
@karlludwigweise The usual part here is that there weren't any changes at all pertaining to the build scripts. If the script is the exact same as before then it shouldn't be related to the SDK. 

This error means the sentry.properties file isn't correctly loaded. I would check that the script is being called in the same directory as the `sentry.properties` file as that's where it seems to be exported. You can also try playing around with the `export SENTRY_PROPERTIES=sentry.properties` line to make sure it's seeing the file. Otherwise a workaround if nothing else works is you can define the organization as an argument to the command `--org ***`.

**Comment by karlludwigweise** [comment]
I am closing this issue, because it is resolved for me now. I did nothing to fix it.

**Comment by jamesdunay** [comment]
I've just started running into this issue after upgrading from 1.9.0 to 2.6.0.  It happens when I attempt to archive the build. `sentry.properties` is in the root of the iOS folder. Can recreate easily by running `../node_modules/@sentry/cli/bin/sentry-cli react-native xcode`

Though the docs say this... So does it need to be in the iOS Folder or the root of the RN project?
`Before you begin, you need to have already created a sentry.properties file at the root of your React Native project. An example of this properties file can be found in Sentry's GitHub.`

**Comment by jennmueng** [comment]
@jamesdunay It should be in the `ios/` folder

**Comment by jinghongchan** [comment]
is it a good idea to commit the `auth.token` in `sentry.properties` into git? What is an alternative approach if we were to gitignore `sentry.properties`? Is it possible to use ENV or something?

**Comment by ShivamJoker** [comment]
I am trying to run the iOS build on github action but keeps failing because of sentry

**Comment by marandaneto** [comment]
@ShivamJoker raise a new issue with a detailed description if you are having problems
