### ISSUE TITLE
Initialization is forced to be deffered for code push apps

### ISSUE THREAD

**Issue by Gentlee** [getsentry/sentry-react-native#1198]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.9.0

**`react-native` version:** 0.62.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

No link.

**Configuration:**

(`@sentry/react-native`)
```
(async () => {
  const [{ appVersion }, update] = await Promise.all([
    codePush.getConfiguration(),
    codePush.getUpdateMetadata(),
  ]);

  Sentry.init({
    dsn: Config.SENTRY_DSN,
    environment: Config.ENVIRONMENT,
    enabled: !__DEV__,
    debug: __DEV__,
    ...(update
      ? {
          release: `${update.appVersion}+codepush:${update.label}`,
          dist: update.label,
        }
      : null),
  });
})();
```
---
**I have following issue:**

Initialization is asynchronous and sentry doesn't catch errors for quite a lot of time.

**Steps to reproduce:**
Use my code.

**Actual result:**

Initialization is deffered until code push loads its metadata.

**Expected result:**

There should be a way to change release and dist after sentry initialized or please provide some other way to handle this situation.

**Comment by jennmueng** [comment]
Our recommended method for this is to store your app `release` and `dist` in some json like `app.json` or even use the `package.json` version as they get loaded with every code push build instead of using an asynchronous method.

There are the methods `Sentry.setRelease` and `Sentry.setDist` that allow you to set the release and dist after an asynchronous call to get the code push version but they are deprecated. This is because you need the release and dist at the very start of the app open for release health to be attributed to the correct release. Using these methods would lose the release health feature and they could also be removed in a future release.
