### ISSUE TITLE
Get device context on Performance on Android

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-react-native#1291]
This requires a change on Android to `prepareEvent` where an event is taken as an argument and is returned fully enriched.

**Comment by bruno-garcia** [comment]
Related to: https://github.com/getsentry/sentry-java/issues/1234

**Comment by marandaneto** [comment]
cc @denrase

**Comment by marandaneto** [comment]
@jennmueng fix is merged, it'll be published in the next beta version of the Android SDK
we're still not offering the `prepareEvent` method because it'd require a big change so for now we enrich the transactions in the same way as events, it was an easy fix and it'd bring more value right away, so no changes on the RN SDK other than bumping the Android SDK

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-java/releases/tag/5.0.0-beta.4
cc @denrase
