### ISSUE TITLE
Can not use navigation tracing for react-navigation v4: integration.setupOnce is not a function

### ISSUE THREAD

**Issue by maxkomarychev** [getsentry/sentry-react-native#1557]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
@sentry/react-native@2.4.3

### Steps to Reproduce

I wanted to setup tracing for react-navigation according to the official documentation: 

```
import * as Sentry from '@sentry/react-native'

const routingInstrumentation = new Sentry.ReactNavigationV4Instrumentation()

Sentry.init({
    dsn: "..",
    environment: "..",
    integrations: [routingInstrumentation],
})
```

### Expected Result

Instrumentation works

### Actual Result

1. typescript error:
2. 
```
Type 'ReactNavigationV4Instrumentation' is missing the following properties from type 'Integration': name, setupOncets(2739)
```

2. runtime crash error:

```
 TypeError: integration.setupOnce is not a function. (In 'integration.setupOnce(hub_1.addGlobalEventProcessor, hub_1.getCurrentHub)', 'integration.setupOnce' is undefined)
```

**Comment by saxenanickk** [comment]
What was the resolution here?

**Comment by krystofwoldrich** [comment]
Usually errors like this are caused by a mismatch of the RN SDK dependencies. 

The RN SDK is only compatible with one version of the JS SDK. See the `package.json` to know the exact version. 

https://github.com/getsentry/sentry-react-native/blob/main/packages/core/package.json#L72

If your project or other dependencies use the JS SDK of a different version, this can cause the mentioned error.

---

Also note that the current version of the RN SDK doesn't support React Navigation version 4 anymore.
