### ISSUE TITLE
Document how to initialize the native SDKs first

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-react-native#1631]
From: https://twitter.com/grifotv/status/1407022107997970437

Users often want to be able to init the native SDKs programatically, before the JS layer even starts. This allows Sentry to capture errors in React Native itself or anything that happens after the Sentry native SDK is initialized (the first thing that happens in the app).

All the features required for this exist but there are not documentation for it.

We need to add user facing docs (docs.sentry.io) about how to configure Sentry with native crash reporting first, and it's pros and cons.

**Comment by grifotv** [comment]
@bruno-garcia thanks for this! I would be greatly appreciated some docs for sure. Even a couple of links to Github issues might be good enough.

We currently use Sentry in our RN app but were considering switching to a different service due to this. Great to hear it's doable with Sentry and that the team is promptly trying to help.

**Comment by bruno-garcia** [comment]
The option that controls this is `autoInitializeNativeSdk` but I'll defer to @jennmueng who knows best how it works to give us a quick pointer here before we land the complete docs.

**Comment by jennmueng** [comment]
@grifotv Yes, you would pass `autoInitializeNativeSdk: false` to the `Sentry.init` call on JS, this disables the SDK from handling the initialization of the native layer. You would then initialize the native layer SDK manually, following the guides here for [Android](https://docs.sentry.io/platforms/android/configuration/manual-init/) and [iOS](https://docs.sentry.io/platforms/apple/guides/ios/#configure).

This should catch any crashes that occur before the JS engine launches. We should definitely work to document this but what I think would be significant if we can make the SDK catch these by default right?

**Comment by marandaneto** [comment]
> This should catch any crashes that occur before the JS engine launches

not entirely true, JS engine also starts via ContentProvider on Android, if you start the Sentry Android SDK manually, disabling the auto-init mode, the JS engine starts before the Sentry Android SDK.
If you keep the auto-init mode enabled, the JS engine might start before or after the Sentry Android SDK, since the init. order is computed at runtime by the OS iirc.

maybe @philipphofmann knows the init order on iOS

**Comment by grifotv** [comment]
> @grifotv Yes, you would pass `autoInitializeNativeSdk: false` to the `Sentry.init` call on JS, this disables the SDK from handling the initialization of the native layer. You would then initialize the native layer SDK manually, following the guides here for [Android](https://docs.sentry.io/platforms/android/configuration/manual-init/) and [iOS](https://docs.sentry.io/platforms/apple/guides/ios/#configure).

@jennmueng Thanks for this.

------------

> not entirely true, JS engine also starts via ContentProvider on Android, if you start the Sentry Android SDK manually, disabling the auto-init mode, the JS engine starts before the Sentry Android SDK.
If you keep the auto-init mode enabled, the JS engine might start before or after the Sentry Android SDK, since the init. order is computed at runtime by the OS iirc.

@marandaneto @philipphofmann Does it mean there will be different instructions for Android and iOS with regards to the `autoInitializeNativeSdk` value? Or should we always set `autoInitializeNativeSdk: true` and if the JS `Sentry.init` is called after the Sentry iOS/Android SDK was already started, it is ignored?

**Comment by grifotv** [comment]
Looks like if I use v[2.4.3](https://github.com/getsentry/sentry-react-native/releases/tag/2.4.3)+ which includes #1529 #1516, it should be safe to use `autoInitNativeSdk: false` in Android too. Is that correct?

**Comment by marandaneto** [comment]
> Looks like if I use v[2.4.3](https://github.com/getsentry/sentry-react-native/releases/tag/2.4.3)+ which includes #1529 #1516, it should be safe to use `autoInitNativeSdk: false` in Android too. Is that correct?

yes if the Sentry Android SDK inits first.
No if the JS engine inits before and try to capture something but the Sentry Android SDK is not inited yet.

**Comment by grifotv** [comment]
@marandaneto In that case I'm not sure what the recommended setup is for Android.

**Comment by marandaneto** [comment]
@grifotv that's why we have this open issue, to figure it out, find corner cases, and document it, stay tuned.

**Comment by bruno-garcia** [comment]
If RN also uses ContentProvider, one strategy would be to opt-out of the ContentProvider initialization of React Native:, i.e:

```
<provider
    android:name="com.facebook.react.modules.blob.BlobProvider"
    android:authorities="${applicationId}.whatevertheirprovideris"
    tools:node="remove"  />
```

** Btw they only have this `BlobProvider` is this initializing?

I only see this one here: https://github.com/facebook/react-native/search?q=ContentProvider

Then you're on your own to init React Native from the Java/Kotlin code. You can either rely on Sentry auto init (add DSN to `AndroidManifest.xml`) or you can opt-out, and also init Sentry programatically. In that case init Sentry first, RN after.

**Comment by marandaneto** [comment]
yep, that does not block us from documenting it, but before doing so, figuring out how it really works.
also need to check if the RN engine itself does have transitive dependencies that may register more `ContentProvider` etc
