### ISSUE TITLE
CodePush + Hermes Source maps not reflecting

### ISSUE THREAD

**Issue by hossamelbery** [getsentry/sentry-react-native#1662]
### Environment

How do you use Sentry?
sentry.io

Which SDK and version?
"@sentry/react-native": "^2.6.0"
Reactnative v 64.2

### Steps to Reproduce

1. Generate a new codepush update with source maps with hermes enabled
2. upload source maps to sentry with a custom release, dist names using this command

      ``` sentry-cli react-native appcenter \```
         ``` ${projectName} ${PLATFORM} "./build/release/$PLATFORM/CodePush" \```
          ```--deployment "Production" \```
          ```--release-name "android.4.0.7+codepush:4070-03" \```
         ``` --dist "4070-03" ```

3. crash the app with a javascript error

### Expected Result

Get the error with a full stack trace

### Actual Result

I got the error with just minified frames event though that the error release and dist is the same with the artifacts as seen in the images

![s2](https://user-images.githubusercontent.com/71596988/125209824-f0a3b180-e29b-11eb-8019-2a3eea4d6a2c.PNG)
![s1](https://user-images.githubusercontent.com/71596988/125209825-f1d4de80-e29b-11eb-8391-4e4e6f9f8cf4.PNG)

**Comment by alex-a-pereira** [comment]
Hey I just had to implement this same thing for my team! Originally I thought it was a hermes issue (the 0 B bundle is what made me think that) but it turned out just to be an issue of matching up the sentry release/distr properly.

I'm not 100% certain on everything I'm saying here but it's working for us. Here's what I found:

Sentry needs a few things for sourcemaps to show up correctly:
- sourcemaps must be upload for correct release (duh)
- sentry release/dist (at runtime, what you call `Sentry.init` with) must match up 100% with the release that sourcemaps were uploaded for.

There's a few pieces to making sure these match up:
1. figure out what you'd like to use to make the JS runtime match up with the proper release/distr in sentry
2. figure out a way to make the JS runtime aware of the release/distr to use when calling `Sentry.init`
    a. additionally you should likely add a tag to make consumers aware that it's a codepush distr

For part 1, we chose to concat the native version that's used to release to app store (e.g. 1.4.0) with the commit hash. This code looks like like:

```bash
# pull native version (e.g. 1.4.0) out of pbxproj file
IOS_NATIVE_VERSION=`cat ios/parentApp.xcodeproj/project.pbxproj | grep -m 1 MARKETING_VERSION | xargs | sed "s/^MARKETING_VERSION = \(.*\);$/\1/" | xargs`
# sentry distr name is the short commit hash of HEAD
SENTRY_DIST_NAME=$(git rev-parse --short HEAD)
# release name is a combination of app identifier, native version, and a concat'd "tag (+ota:) and commit hash)
SENTRY_RELEASE_NAME_IOS="com.our_company.our_app_name@$IOS_NATIVE_VERSION+ota:$SENTRY_DIST_NAME"
```

When uploading source maps, you'll want to specify both the sentry release (the whole string from above) and the distr (just the commit hash)
```bash
sentry-cli react-native appcenter APPCENTER_TEAM/APPCENTER_APP_NAME \
  ios PATH_TO_OUTPUT_DIR_HERE \
  --deployment $CP_DEPLOYMENT_NAME \
  --release-name $SENTRY_RELEASE_NAME_IOS \
  --dist $SENTRY_DIST_NAME
```

For part 2, we currently have some issues so I'd reccomend brainstorming another way, but here's what we did. Since we don't use the codepush release description (usually used for release notes), we decided to put a JSON string in there specifying data related to how to init sentry.
```bash
CODEPUSH_DESCRIPTION_IOS='{"sentryEnv": "'"$CP_DEPLOYMENT_NAME"'", "sentryRelease": "'"$SENTRY_RELEASE_NAME_IOS"'", "sentryDist": "'"$SENTRY_DIST_NAME"'", "releaseNotes": ""}'
```

Which ends up looking something like:
```json
{
  "sentryEnv": "production",
  "sentryRelease": "com.our_company.our_app_name@1.4.0+ota:2410d047",
  "sentryDist": "2410d047"
}
```


you can then do in your code something like:
```js
codePush.getUpdateMetaData.then(metaData => {
  if(metaData) {
    const descr = JSON.parse(metaData).description
    Sentry.init({
      dsn: SENTRY_DSN_HERE,
      environment: descr.sentryEnv,
      release: descr.sentryRelease,
      dist: descr.sentryDist
    })
  }
})
```

**Comment by jennmueng** [comment]
@alex-a-pereira One note, we don't recommend calling `Sentry.init` inside `codePush.getUpdateMetaData` as its an asynchronous call that would delay the initialization of Sentry and not catch any errors/crashes that happen before the call is completed.

Usually we recommend storing your release, environment, and release values somewhere with your bundle that you'll be able to read right away as soon as the JavaScript engine initializes. For example, in `package.json` and reading the version from there.

This is an incompatibility with how CodePush recommends people use the versioning from `getUpdateMetadata` and Sentry that needs to be initialized as soon as possible.

**Comment by jennmueng** [comment]
@hossamelbery Sorry for the late reply, I was on vacation the past 2 weeks. Your sourcemaps are being detected correctly but they're not bundled correctly. I'm pushing a documentation update for Hermes right now and will add a second comment shortly.

**Comment by jennmueng** [comment]
Here is the update to the Hermes sourcemaps documentation: https://github.com/getsentry/sentry-docs/pull/3391

Temporary deployment link:
https://sentry-docs-5x88knmcu.sentry.dev/platforms/react-native/manual-setup/hermes/#custom-source-maps

Please let me know if this works.

**Comment by alex-a-pereira** [comment]
> @alex-a-pereira One note, we don't recommend calling `Sentry.init` inside `codePush.getUpdateMetaData` as its an asynchronous call that would delay the initialization of Sentry and not catch any errors/crashes that happen before the call is completed.
> 
> Usually we recommend storing your release, environment, and release values somewhere with your bundle that you'll be able to read right away as soon as the JavaScript engine initializes. For example, in `package.json` and reading the version from there.
> 
> This is an incompatibility with how CodePush recommends people use the versioning from `getUpdateMetadata` and Sentry that needs to be initialized as soon as possible.

Thanks, we changed out approach for this reason. We were previously initting sentry twice (once at JS bundle mount, again after `getUpdateMetadata` promise resolves) which was casuing some issues. I've updated my comment above in case anyone else stumbles across this thread
