### ISSUE TITLE
multiple DSNs reported independently

### ISSUE THREAD

**Issue by gintamamadao** [getsentry/sentry-react-native#1726]
is it possible to have multiple DSNs reported independently, the current @sentry/react-native config seems like a single instance, the sentry init method executed later will override the previous init config, finally only one DSN being reported.

**Comment by jennmueng** [comment]
@gintamamadao You can use multiple DSNs by initializing separate clients. I recommend initializing a global instance as usual by calling the usual `Sentry.init` to capture all errors. Then you can then follow this [code sandbox](https://codesandbox.io/s/l7qrkjn7nm) but instead of using `@sentry/browser`'s `Sentry.BrowserClient`, you would use `@sentry/react-native`'s `Sentry.ReactNativeClient`.

**Comment by gintamamadao** [comment]
It solved my problem, thanks a lot!
