### ISSUE TITLE
The bundle size is too large 430KB

### ISSUE THREAD

**Issue by TangShengda** [getsentry/sentry-react-native#1733]
The bundle package volume is too large 430KB

**Comment by ku8ar** [comment]
@TangShengda Exactly. This is what it looks like in our project

![Zrzut ekranu 2021-08-17 o 09 21 58](https://user-images.githubusercontent.com/16975059/129754034-e75ab025-aecf-4f16-ac84-48b88458ef5e.png)

Modules marked in red seem completely unnecessary.

The problem seems to arise from importing entire modules:
```
// bad
import { addGlobalEventProcessor } from "@sentry/core";

//good
import addGlobalEventProcessor from "@sentry/core/src/addGlobalEventProcessor";
```

I tried to manually change these imports in `@sentry/react-native` package, but this applies to all `@sentry/*` packages.

For example, `@sentry/browser` is not directly imported into `@sentry/react-native`, but we import it all anyway.

As a result, the `@sentry/react-native` package is the second largest package in our app (because the largest is of course `react-native`). It even takes up more space than entire react-navigation package.

**Comment by jennmueng** [comment]
Let's follow the discission over on the sentry-javascript repo:  https://github.com/getsentry/sentry-javascript/issues/2707

**Comment by jayshah-swiggy** [comment]
same as https://github.com/getsentry/sentry-react-native/issues/1818

**Comment by marandaneto** [comment]
related to https://github.com/getsentry/sentry-react-native/issues/759

**Comment by marandaneto** [comment]
Ideally, we'd migrate to the Sentry JS SDK 7.x and get the bundle size improvements for free, which requires migration.
https://github.com/getsentry/sentry-javascript/issues/4240

**Comment by marandaneto** [comment]
The effort depends on who does the migration to Sentry JS SDK, maybe we do the migration for user feedback or attachments or client reports, if that's the case, then the  effort is just `Small`.

**Comment by marandaneto** [comment]
There were a few improvements related to bundle size on the JS SDK and Android SDK, the RN SDK got it for free, please upgrade to the latest version (4.x) and let us know if that helped, thanks.
