### ISSUE TITLE
Sentry for sdk's

### ISSUE THREAD

**Issue by irohitb** [getsentry/sentry-react-native#1782]
How can we have sentry in our sdk? 

The problem is that if someone using our sdk also uses sentry then it's going to have problem with DSN's (sentry doesn't support multiple DSN's)

One way I can think is to catch the app crash exception explicitly, send the log manually

but besides that, is there any other way? where don't have to manually catch and send logs?

**Comment by marandaneto** [comment]
instead of using the `Sentry` static class, consider creating your own instance of `Hub`, https://docs.sentry.io/platforms/react-native/enriching-events/scopes/ but obviously, you have to manually catch and report the exceptions.
for unhandled exceptions, you also have to register to the hooks manually, the Sentry SDK is meant to be used by final Apps and not 3rd party libs.
