### ISSUE TITLE
sync or not sync the performance options `tracesSampleRate` and `tracesSampler` from JS to iOS

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-react-native#1867]
since RN uses the initWithDict option, those options are synced down to iOS but not for Android, should we stop doing it or sync it down to Android?

side effect is that some data might be double-reported eg Cold/Warm App start.

**Comment by bruno-garcia** [comment]
We agreed not to propagate this setting, since the performance support at this time is focused on the layer where it operates. So enabling iOS transactions on a hybrid app, results in double reporting a screen load without actionable information for the app developer for the native transaction.

On apps that have hybrid + native screens, docs could explain how to enable both (init the native layer programatically) and filter out the auto transaction created in the native SDK as a result of rendering a hybrid SDK (where the transaction comes from the hybrid SDK instead).

**Comment by marandaneto** [comment]
closed by https://github.com/getsentry/sentry-react-native/pull/1872
