### ISSUE TITLE
Duplicate issue reporting on iOS

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-react-native#2069]
More context: https://forum.sentry.io/t/react-native-sdk-ios-crash-produces-2-issues-while-i-expect-one/16067

**Comment by marandaneto** [comment]
@fakeheal Could you please link to the Sentry project that has these issues?

**Comment by bruno-garcia** [comment]
> Seems like RN is throwing an Objective-C exception and the cocoa SDK is capturing that too.
It’s possible we’ll need to filter out such exception when using the cocoa SDK in the React Native context.

![image](https://user-images.githubusercontent.com/1633368/155380496-cee174f9-b1c2-4dc5-95f1-07bb9e7eb0ee.png)


Possible solution: In beforeSend in the bridge code for the cocoa SDK we can skip these events.

**Comment by fakeheal** [comment]
I'll just paste here what I posted in the forum. My project is & uses: 

[SDK](https://sentry.io/organizations/itodorova-dev/issues/3023302476/?project=6209679&query=is%3Aunresolved#sdk)
**Name**	sentry.javascript.react-native
**Version**	3.2.13

[SDK](https://sentry.io/organizations/itodorova-dev/issues/3023302422/?project=6209679&query=is%3Aunresolved#sdk)
**Name**	sentry.cocoa
**Version**	7.9.0

Thank you for confirming it's a bug and not an incorrectly setup project 😅 , because it was driving me crazy.

> Possible solution: In beforeSend in the bridge code for the cocoa SDK we can skip these events. Not in a way that skips all Obj-C exceptions though

I will try implementing this idea and see if those events can be filtered out reliably.

**Comment by marandaneto** [comment]
@fakeheal thanks, can you provide your SDK init - code snippet? thanks

**Comment by fakeheal** [comment]
@marandaneto Sure!  [`@env`](https://www.npmjs.com/package/react-native-dotenv) is a dot env package for RN, but SENTRY_DSN and APP_ENV are simple strings with my DNS string and `staging` for `APP_ENV`.

```
import {SENTRY_DSN, APP_ENV} from '@env';

// .... 

Sentry.init({
  dsn: SENTRY_DSN,
  environment: APP_ENV,
  tracesSampleRate: 1.0,
});
```

**Comment by marandaneto** [comment]
@fakeheal do you do any [Manual setup or configuration](https://docs.sentry.io/platforms/react-native/manual-setup/) besides the code snippet above? or do you use Hermes, CodePush, RAM Bundles, or something different than usual?

I ask because I can't reproduce it using a fresh new project.

Can you provide a minimal reproducible example on GH? that would ease the debugging and the fix if any is needed, thanks.

**Comment by fakeheal** [comment]
@marandaneto I don't use any of the mentioned stuff, however I couldn't also reproduce the problem in a new repo. I am sorry for wasting your time! I'll try fixing my project.
