### ISSUE TITLE
Bump Script is throwing an error and failing CI

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-react-native#2333]
Exception: /home/runner/work/_temp/ghwf/scripts/update-dependency.ps1:37
Line |
  37 |  …             throw "Script execution failed: $Path $action $value | ou …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Script execution failed: scripts/update-wizard.sh get-version 
     | | output: Failed to find the plugin version in
     | /home/runner/work/sentry-react-native/sentry-react-native/scripts/../package.json
Error: Process completed with exit code 1.

https://github.com/getsentry/sentry-react-native/runs/7127617986?check_suite_focus=true
Introduced by https://github.com/getsentry/sentry-react-native/pull/2321

**Comment by marandaneto** [comment]
cc @vaind

**Comment by vaind** [comment]
The problem is in parsing the version, the script currently doesn't expect "^" at the beginning: https://github.com/getsentry/sentry-react-native/blob/6e37f6755b18f7e18436f69ac6ef32209a18f2b8/package.json#L52

Changing the script is not a problem, the question is whether we want the updater to bump to a specific version, i.e. without the "^", or preserve that declaration.

**Comment by marandaneto** [comment]
@vaind let's pin the version, we release our SDK often, so it's not an issue, we can remove the `^` if necessary.
