### ISSUE TITLE
Attach screenshot

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-react-native#2362]
Add option `attachScreenshot` that when opt in, attached a screenshot on error events.

**Comment by marandaneto** [comment]
It's not just adding the `attachScreenshot` flag.

On iOS, native hard crashes would work, but the JS errors won't contain the screenshot, because we call `captureEnvelope` or `storeEnvelope` and those functions won't attach the screenshot before sending it over to Sentry.

On Android, We always store the envelope on the disk, and the file observer will pick it up and enrich the event with device context, that's already too late and the view might not be up to date anymore, I have to debug the Android bits once more.

I feel that https://github.com/getsentry/team-mobile/issues/11 should be addressed first with this issue in mind.
cc @bruno-garcia

**Comment by bruno-garcia** [comment]
If we're triggering the screenshot from JS through the bridge it's possible the view will change, no? So possibly not exactly what was on the screen at that time? It's fine if that's the case, just good to understand and document it.

> I feel that https://github.com/getsentry/team-mobile/issues/11 should be addressed first with this issue in mind.

Not sure this one affects things as much. We can take care of screenshots on each layer: In JS if there's an error, we get a screenshot through the bridge and pass it down to the native layers in the envelope. It doesn't need to live in the JS-land either, we could do all of that in the bridge if that makes things easier. 
For the native errors we just pass the flag down so they add screenshots when they capture errors on those layers.

Would that work?

So we need to figure out:
* Might require: #1327 
* https://github.com/getsentry/sentry-java/issues/2185

**Comment by marandaneto** [comment]
> If we're triggering the screenshot from JS through the bridge it's possible the view will change, no? So possibly not exactly what was on the screen at that time? It's fine if that's the case, just good to understand and document it.

If we `await` the calls, technically the view is the same because we are in the calling thread.

> The first issue is that the currentActivity is null because the Android SDK is inited after the very first Activity is created.

This is still an issue, we'd need to find a way to set the `currentActivity` via the RN SDK, maybe the RN plugin should implement its own logic for screenshots, and the EventProcessor just exposes the methods to not duplicate the same logic, similar to Slow/frozen frames.
