### ISSUE TITLE
Disable integration in production but have packaged installed?

### ISSUE THREAD

**Issue by donni106** [getsentry/sentry-react-native#2371]
Is there a way to have @senty/react-native integrated but disabled for some production builds?
I am using expo and have tried some overrides in my projects react-native.config.js but without a result. Sentry is still part of the resulting bundle. 
What else can I provide to be more useful/descriptive here?

**Comment by bruno-garcia** [comment]
I don't believe Sentry will not end up in the final app simply if you avoid calling `init`. Perhaps if there's no call to the SDK itself at all, in which case dead code elimination could do it's thing. Maybe something @marandaneto knows more details.

So in short: I don't think it's possible, but it's a more general React Native question rather than Sentry

**Comment by marandaneto** [comment]
React Native does not do treeshaking, https://github.com/facebook/metro/issues/227#issuecomment-583358386

If you just want to disable the SDK, either don't call `Sentry.init` or set a DSN to empty `options.dsn = ''`, but the package will be installed anyway.
