### ISSUE TITLE
Can't filter breadcrumbs on Android

### ISSUE THREAD

**Issue by ejain** [getsentry/sentry-react-native#3090]
**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.4.0

**`react-native` version:** 0.70.9

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[BLOOMTEXT-MOBILE-NX](https://bloomtext.sentry.io/issues/4208764152/events/9e4d336003ca4d118b951aa38fa4710c/?project=5751219)

**Configuration:**

(`@sentry/react-native`)
```
    Sentry.init({
      dsn: SENTRY_DSN,
      enableAppHangTracking: false,
      enableWatchdogTerminationTracking: false,
      beforeBreadcrumb (breadcrumb) {
        return breadcrumb.category === "action" ? breadcrumb : null
      },
    })
```

Also tried:
```
     ...
      integrations: function (integrations) {
        return integrations.filter(function (integration) {
          return integration.name !== "Breadcrumbs"
        })
      },
     ...
```

(`AndroidManifest.xml`)
```
<manifest>
  <application>
    ...
     <meta-data android:name="io.sentry.breadcrumbs.activity-lifecycle" android:value="false" />
     <meta-data android:name="io.sentry.breadcrumbs.app-components" android:value="false" />
     <meta-data android:name="io.sentry.breadcrumbs.app-lifecycle" android:value="false" />
     <meta-data android:name="io.sentry.breadcrumbs.system-events" android:value="false" />
     <meta-data android:name="io.sentry.breadcrumbs.user-interaction" android:value="false" />
   </application>
</manifest>
```

---
**I have following issue:**

Despite filtering on `breadcrumb.category === 'action'`, `network.event` and `app.lifecycle` breadcrumbs are captured. Disabling automatic breadcrumbs in the Android manifest [as described here](https://docs.sentry.io/platforms/android/enriching-events/breadcrumbs/#disable-automatic-breadcrumbs) doesn't suppress these, either.

**Steps to reproduce:**
- Trigger any error

**Actual result:**

Breadcrumbs contain not just `action` but also `network.event` and `app.lifecycle` breadcrumbs. On iOS, there are even more categories, including 'ui.lifecycle' and `touch`...

**Expected result:**

Breadcrumbs contain only "action" items.

**Comment by ejain** [comment]
Should add that some breadcrumb categories (e.g. `console`) are being filtered out as expected with this setup.

**Comment by ejain** [comment]
I suspect `beforeBreadcrumb` is only processing "browser" breadcrumbs, but not "native" breadcrumbs -- if that makes sense.

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the message and details.

`beforeBreadcrumb` callback is executed only for JS Breadcrumbs. Native breadcrumbs are added by our integration later on. To only receive `breadcrumb.category === 'action'` you can filter the final breadcrumbs in 	`beforeSend`.

At the moment this won't work on Android due to the current way of scope synchronization. More information about the issue [here](https://github.com/getsentry/team-mobile/issues/11).

The `AndroidManifest.xml` options are ignored because [the RN SDK initializes the Android SDK](https://github.com/getsentry/sentry-react-native/blob/34aba0802bf802288f91fada55c0b133252fe67f/android/src/main/java/io/sentry/react/RNSentryModuleImpl.java#L106). To change the Android Breadcrumbs options you would need to [initialize the SDK manually](https://docs.sentry.io/platforms/react-native/manual-setup/native-init/).

**Comment by ejain** [comment]
Thanks for the explanation -- good to know that this is a known issue/limitation.

**Comment by krystofwoldrich** [comment]
I'll close this issue since the core problem is described in https://github.com/getsentry/team-mobile/issues/11
