### ISSUE TITLE
Highlighted line is off by one line on non existing property

### ISSUE THREAD

**Issue by the-skins-app** [getsentry/sentry-react-native#3239]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 0.0.0

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[[Link to issue]](https://skins-bk.sentry.io/issues/4389521970/?project=4505131310841856&query=is%3Aunresolved&referrer=issue-stream&stream_index=0)

**Configuration:**

(`@sentry/react-native`)
```
const bundleId = Platform.OS === 'ios' ? config.bundleIdIos : config.bundleIdAndroid

const { appVersion, label } = await codePush.getUpdateMetadata()
const release = `${bundleId}@${appVersion}+codepush:${label}` // eg: com.foo.bar@1.9+codepush:v68

Sentry.init({
    dsn: "https://518d6f8ce5f44c12a464be5ff5e614be@o4505131309203456.ingest.sentry.io/4505131310841856",
    tracesSampleRate: .1,
    release,
    dist: label
});
```

---
**I have following issue:**

The sourcemap is one line off. In the following screenshot, line 43 should be highlighted, not line 42:

![image](https://github.com/getsentry/sentry-react-native/assets/132851402/440797a9-3641-45be-8704-54d4dae3cc7c)

The android version of my app does not have this issue.

**Steps to reproduce:**

I'm using these scripts to generate the source maps:

```json
{
 "ios:deploy": "npm run appcenter:login && npm run ios:codepush:release && npm run ios:sentry",
 "appcenter:login": "appcenter login --token foobar",
 
 "ios:getNativeVersion": "sed -n '/MARKETING_VERSION/{s/MARKETING_VERSION = //;s/;//;s/^[[:space:]]*//;p;q;}' ./ios/skins.xcodeproj/project.pbxproj",
 "ios:getCodePushVersion": "appcenter codepush deployment list --app foo/bar | sed -n -e 's/^\\(.*\\)\\(Label: \\)\\(v[0-9]*\\) \\(.*\\)$/\\3/p'",

 "ios:codepush:release": "rm -rf sentry && appcenter codepush release-react --extra-bundler-option=--reset-cache --extra-bundler-option=--minify --extra-bundler-option false -m -a foo/bar -d Production --sourcemap-output './sentry/CodePush/main.jsbundle.map' --output-dir './sentry'",

 "ios:sentry": "export SENTRY_PROPERTIES=./ios/sentry.properties; v=$(npm run --silent ios:getNativeVersion) && c=$(npm run --silent ios:getCodePushVersion) && sentry-cli react-native appcenter foo/bar ios './sentry/CodePush' --bundle-id 'com.foo.bar' --version-name $v --dist $c --deployment Production",
}
```

**Actual result:**

highlighted line is 42

**Expected result:**

highlighted line is 43

**Comment by kahest** [comment]
Hey @the-skins-app, thanks for reporting and the details - we'll investigate. Please let us know if you see something similar in other parts of your code.

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the message and the details.

It looks like there is a difference between Sentry symbolication and `metro-symbolicator` which points to the correct line number 43.

Does this happen only with CodePush updates or also with full app releases?

Does this still happen, when you send a new error?

**Comment by Swatinem** [comment]
The off-by-one seems to be here somewhere:

```
<Token src/Screens/HomeScreen.tsx:80:23 (0:985283)>
<Token src/Screens/HomeScreen.tsx:81:12 name=thisVariableDoesNotExist (0:985288)>
```
The first token is the one we find, while the second token is the right one.

We are doing a `-1` on both line and column, as the stack traces report those as 1-indexed, whereas the sourcemap tokens themselves contain those as 0-indexed.

So we are internally actually looking for `985287` and find the previous token. I’m just wondering why the other tools are doing the right thing here.

**Comment by Swatinem** [comment]
Some digging in the past later:

Seems like we have been adjusting columns ever since https://github.com/getsentry/sentry/commit/bc8fa24c2b516760d502b23c6e42c75e07b27628 / https://github.com/getsentry/sentry/pull/5922
(And adding +1 when the token comes back: https://github.com/getsentry/sentry/commit/6867a455526eeff810490771482b24dfdb31e535#diff-5649208c3eac2367f8d3130a299d7c3cd3020aa4c1a21f1d4ea57b80de38ef34R600)

When porting that logic to symbolicator, we have cargo-culted that behavior as well:

https://github.com/getsentry/symbolicator/commit/70451dc2548bc0b20d48cadd73b1d2a30e48f69d#diff-d8382530b3ce9204a7a4c01b6ff3bde446870d29db23b45b8236281c5a5eea7cR183-R184
interestingly, backwards adjusting was added later:
https://github.com/getsentry/symbolicator/commit/eb6b197f67e17bdd3b69d6a7152e42de2829aa29#diff-d8382530b3ce9204a7a4c01b6ff3bde446870d29db23b45b8236281c5a5eea7cR166-R168

Even though other tools agree that columns are 0-based, both in stack traces as well as in the sourcemaps.

https://github.com/mozilla/source-map/blob/master/lib/source-map-consumer.js#L472-L475
https://github.com/tc39/source-map-spec/blob/1ac019b79757d9cea70401fa530a78b6c062feb8/source-map-rev3.md?plain=1#L110

I’m questioning my sanity a bit by now.

**Comment by Swatinem** [comment]
Okay, @mitsuhiko cleared up the confusion. While the JS/SourceMap ecosystem may agree that columns are 0-based, Sentry itself uses 1-based column in its event payloads and the UI.

So possibly the SDK fails to adjust the column before it sends it over to Sentry?

**Comment by the-skins-app** [comment]
@krystofwoldrich it only occurs with CodePush, not with Native builds. Yes, new errors are still one line off, but I did notice one that happened to be correct a while ago. I'm not sure why.

@Swatinem thank you for looking into this. You seem to be on the scent.

**Comment by krystofwoldrich** [comment]
- Line/Column indexing in RN https://github.com/facebook/react/issues/21792#issuecomment-873171991

Differs based on the engine JSC/Hermes.
