### ISSUE TITLE
Blank red screen error with 5.17.0 and `sentry-expo`

### ISSUE THREAD

**Issue by dnelsonlivecurrence** [getsentry/sentry-react-native#3555]
**OS:**
- [ ]  Windows
- [X ]  MacOS
- [ ]  Linux

**Platform:**
- [X ]  iOS
- [ ]  Android

**SDK:**
- [5.17.0]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)
- [ ~7.0.0]  `sentry-expo`

**SDK version:** 0.0.0

**`react-native` version:** ^0.73.2

**Are you using Expo?**
- [ X]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  environment: appSettings.get('STAGE'),
  release: ExpoAppJson.expo.version,
  enableInExpoDevelopment: true,
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have the following issue:**

[Description]

**Steps to reproduce:**
- Upgrade to 5.17.0
- Experience Error

**Actual result:**

I'm seeing a blank red screen pop up after the app loads following an upgrade to 5.17.0 in iOS.

<img width="468" alt="Screenshot 2024-01-26 at 8 40 48 AM" src="https://github.com/getsentry/sentry-react-native/assets/127855703/3a4b27ef-79ee-4072-9567-249a6b828901">

The Extra info button doesn't provide any context, but if I downgrade @sentry/react-native this goes away.

<img width="512" alt="Screenshot 2024-01-26 at 8 40 53 AM" src="https://github.com/getsentry/sentry-react-native/assets/127855703/65a05fd0-046d-4b40-a66a-7aade9227f6e">

If I dismiss the error pop up the app functions correctly.

I don't get any errors in the console or in Xcode. But there is a strange array of numbers that appear:

<img width="414" alt="Screenshot 2024-01-25 at 2 57 51 PM" src="https://github.com/getsentry/sentry-react-native/assets/127855703/245c26a8-7909-4b6e-97b1-2f9d2907ebf5">

**Expected result:**

Expected this strange pop up to not occur.

**Comment by krystofwoldrich** [comment]
Hi @dnelsonlivecurrence,
thank you for the message, 

I see that you are using `sentry-expo` in combination with `@sentry/react-native`. This is not supported since `5.16.0`.

[getsentry/sentry-react-native@5.16.0 (release)](https://github.com/getsentry/sentry-react-native/releases/tag/5.16.0) deprecates `sentry-expo` and includes Expo out-of-the-box support.

Migration guides available:
- [expo/fyi@main/sentry-expo-migration.md](https://github.com/expo/fyi/blob/main/sentry-expo-migration.md?rgh-link-date=2024-01-21T21%3A53%3A31Z)
- [docs.sentry.io/platforms/react-native/migration/sentry-expo](https://docs.sentry.io/platforms/react-native/migration/sentry-expo/)

**Comment by dnelsonlivecurrence** [comment]
Thanks, missed that!
