### ISSUE TITLE
Make sentry-expo-upload-sourcemaps read ENV files

### ISSUE THREAD

**Issue by mrljsh** [getsentry/sentry-react-native#3569]
The ﻿sentry-expo-upload-sourcemaps script currently requires users to manually set environment variables when invoking the command-line interface. This process could be streamlined by adding support for automatically reading environment variables from ﻿.env files.

I would make PR for this but I am unsure if you would use dotenv or some other external tool for reading .env files.

**Comment by krystofwoldrich** [comment]
@mrljsh Thank you for creating a separate issue,
please feel free to create a PR!

Thank you for considering the inclusion of other libraries, since we will likely only need the parse function of `dotenv`, we can vendor it. You can copy it from the link and allow maintainers to edit the PR we will add the appropriate license and annotations.

https://github.com/motdotla/dotenv/blob/cfd735d7d00f01e3772a35b541b1b141fd5a5c5c/lib/main.js#L9-L48
