### ISSUE TITLE
Dependency on deprecated version of sentry-cocoa 8.34.0

### ISSUE THREAD

**Issue by koreus7** [getsentry/sentry-react-native#4062]
MacOS, iOS
`@sentry/react-native`  5.31.1 
`react-native` 0.72.6
`cocoa-pods`  1.15.2

No Expo, No on premise, normal Sentry install as per latest docs.

---
**I have the following issue:**

When I build pods fail to install because it's trying to pull a deprecated version of sentry-cocoa

See: https://github.com/getsentry/sentry-cocoa/releases/tag/8.34.0-Deprecated

```
[!] Error installing Sentry
[!] /opt/homebrew/bin/git clone https://github.com/getsentry/sentry-cocoa.git /var/folders/yy/6kcn9mkd5svdbqnznwf474f00000gn/T/d20240902-16425-xsautq --template= --single-branch --depth 1 --branch 8.34.0
Cloning into '/var/folders/yy/6kcn9mkd5svdbqnznwf474f00000gn/T/d20240902-16425-xsautq'...
warning: Could not find remote branch 8.34.0 to clone.
fatal: Remote branch 8.34.0 not found in upstream origin
Failed to install Pods:
  command failed with exit status 1 (pod "_1.15.2_" "install" "--no-repo-update"):
    [!] Error installing Sentry
    [!] /opt/homebrew/bin/git clone https://github.com/getsentry/sentry-cocoa.git /var/folders/yy/6kcn9mkd5svdbqnznwf474f00000gn/T/d20240902-16425-xsautq --template= --single-branch --depth 1 --branch 8.34.0
```

**Comment by kahest** [comment]
Thanks for the report. This should not happen, since @sentry/react-native 5.31.0+ depends on sentry-cocoa 8.36.0, so we'll take a look right away.

**Comment by krystofwoldrich** [comment]
Hi @koreus7,
thank you for the message,

we decided to deprecate release 8.33.0 and 8.34.0 of sentry-cocoa due to some reports of potential crashes. 

Please update your `@sentry/react-native` dependency to [5.31.0](https://github.com/getsentry/sentry-react-native/releases/tag/5.31.0) which already uses the fixed sentry-cocoa release. Apologies for the disruption, but we feel it is the best course of action to prevent usage of this release.

--- 

I see you are using the latest `5.31.1` of Sentry RN. Based on the error message your pods are not up to date. Please run `pod update Sentry` or re-create your native code if using Expo Native Code Generation.

**Comment by koreus7** [comment]
@krystofwoldrich Thank you, unfortunately for me this doesn't resolve the issue.

I am using the latest version of `@sentry/react-native` 5.31.1

Please forgive my ignorance if this is a lack of understanding of cocoapods (since I'm a RN dev not an iOS dev) but here is what I've tried:

```
cd ios
pod deintegrate
rm Podfile.lock
rm -rf ./build
pod install --repo-update
pod update Sentry
pod update RNSentry
```

Neither `pod update Sentry` or `pod update RNSentry` make any difference to the generated `podfile.lock` and subsequently the build still tries to pull the deprecated version of Sentry.

**Comment by koreus7** [comment]
Deleted the cache on my build server and now the pods are installing, thanks again @krystofwoldrich 🙂

**Comment by krystofwoldrich** [comment]
@koreus7 Thanks for the update. Happy to hear it works now.
