### ISSUE TITLE
Sentry Source Map Upload Failure During Android Build

### ISSUE THREAD

**Issue by defild9** [getsentry/sentry-react-native#4072]
**OS:**
- [ ]  Windows
- [x ]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x ]  Android

**SDK:**
- [x ]  `@sentry/react-native` 
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.31.0

**`react-native` version:** 0.72.10

**Are you using Expo?**
- [ ]  Yes
- [x ]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'link',
  tracesSampleRate: 1.0,
  _experiments: {
    profilesSampleRate: 1.0,
  },
});

```

---
**I have the following issue:**

During the Android build process for the React Native application, the task :app:createBundleDevelopmentReleaseJsAndAssets_SentryUpload_@1.0+11_11 fails with a non-zero exit value. The error seems to be related to Sentry CLI when attempting to upload the source maps. Specifically, there is a conflict with the URL values being supplied.

**Steps to reproduce:**
Start the Android build process for the React Native application.
Observe the failure during the :app:createBundleDevelopmentReleaseJsAndAssets_SentryUpload task.

**Actual result:**
The build fails with the following error:
`error: Two different url values supplied: `link` (from token), `link/`.
`

**Comment by krystofwoldrich** [comment]
Hi @defild9,
thank you for the message,

this is a message from the Sentry CLI, when the URL read from the Sentry Auth Token does not match the URL supplies in `sentry.properties` or `SENTRY_URL` env.

Changing or removing the URL set manually will fix it.

We also recommend updating Sentry CLI to https://github.com/getsentry/sentry-cli/releases/tag/2.34.0 or newer, where we changed the behaviour to only show warning, instead of failing the upload.

You can also update to https://github.com/getsentry/sentry-react-native/releases/tag/5.31.1 which ships with the fixed CLI.
