### ISSUE TITLE
Any plan to migrate to AndroidX ? 

### ISSUE THREAD

**Issue by rpechayr** [getsentry/sentry-react-native#585]
Hello, 

I am using your library on our app and we had to migrate to AndroidX in order to support some advanced features related to biometric authentication. 

However, react-native-sentry is still using Android support. So whenever we rebuild or app we need to manually change change the code of react-native-sentry to support AndroidX. 

Since I did not find any issue related to this topic, I am asking the question here :)

**Comment by rozPierog** [comment]
This should be high priority right now because RN 0.60 will only support AndroidX (https://github.com/facebook/react-native/releases/tag/v0.60.0-rc.0) so leaving react-native-sentry on Support Library would break build for anyone who is going to update React-Native. 
CC: @HazAT or anyone maintaining this repo

**Comment by HazAT** [comment]
We released a new version of the SDK `@sentry/react-native` which should support AndroidX.
See for more info: https://github.com/getsentry/sentry-react-native/issues/612
