### ISSUE TITLE
NPM: react-native-sentry vs @sentry/react-native

### ISSUE THREAD

**Issue by olethanh** [getsentry/sentry-react-native#666]
On NPM there are two packages which link this repo:

- react-native-sentry on version 0.43.2 which has more download
- @sentry/react-native on version 1.0.6 which is linked from this repo

Is the first one a fake one? A deprecated one? Maybe this should be made clear in the readme

**Comment by leandrosimoes** [comment]
Hi @olethanh, I saw that too and I had the same question about it, but as both are related to the same repo (https://github.com/getsentry/sentry-react-native), I think that the sentry-react-native was used before, then the guys changed the name of the package to @sentry/react-native for a convention. I realized that I was using sentry-react-native with no problems. I'll try to change to the @sentry/react-native one and test, but I think that the code base will be the same, just the package names and version are different. Companies generally keep both packages to avoid breaking changes for the users that were already using with the old name.

**Comment by HazAT** [comment]
Basically what @leandrosimoes wrote :)

We did a major version bump and our react-native SDK will be called `@sentry/react-native`.
Not sure if you are familiar with other Sentry SDKs but the new version is now unified which ultimately should make it easier for our users using Sentry on different platforms to use any SDK.
https://blog.sentry.io/2018/08/08/new-sdk-unified-api-feedback-requested

We didn't deprecate the old SDK yet since we do not want to force anyone to upgrade (yet).

**Comment by olethanh** [comment]
Thanks for the explanations @HazAT @leandrosimoes , this was one of my theory but since I couldn't find any mention of the old name in the git repository I was afraid it was some scammer/phisher that was pushing a fake package on npm. I'm not sure how the linking from npm  to github works and if anyone can pretend to be any github repository or not. Maybe there could be some Upgrade notice in the repository?

**Comment by HazAT** [comment]
@olethanh Good point, see: https://github.com/getsentry/sentry-react-native/blob/master/README.md#upgrade
