### ISSUE TITLE
Appcenter release invalid characters in string [docs]

### ISSUE THREAD

**Issue by Grohden** [getsentry/sentry-react-native#789]
I don't know if this ever worked before, but in the [docs](https://docs.sentry.io/platforms/react-native/codepush/) using:
```javascript
codePush.getUpdateMetadata().then(update => {
        if (update) {
            Sentry.setDist(`${update.appVersion}-codepush:${update.label}`)
        }
})
```
 results in this for me:
![2019-09-20-101134_771x207_scrot](https://user-images.githubusercontent.com/7496871/65329554-132c7e00-db8f-11e9-8ad1-3b5306aa1831.png)

Not sure what is wrong, maybe I need to prepend the package name (com.foo.bar) in the dist?

Oh, btw, this is not a cli issue isn't? if there's a better place for me to open this issue let me know

**Comment by Grohden** [comment]
Seems like the docs have been updated, here's what should be used (`setRelease` instead of `setDist`):

```javascript
codePush.getUpdateMetadata().then((update) => {
  if (update) {
    Sentry.setRelease(update.appVersion + '-codepush:' + update.label);
  }
});
```

gona give it a try and close the issue if it works

**Comment by ptman** [comment]
_dist_re = re.compile(r'^[a-zA-Z0-9_.-]+$')

from: https://github.com/getsentry/sentry/pull/5262/files#diff-da365f8d913a2a9c688f1d2b2e540f2eR59

**Comment by StarryFire** [comment]
1. To deploy changes via codepush, run the following command

```
appcenter codepush release-react --sourcemap-output --app APP_NAME --output-dir ./build -d DEPLOYMENT_NAME
```

2. To upload the sourcemaps of the deployed codebase to sentry, run the following commands

```
export SENTRY_PROPERTIES=./PLATFORM/sentry.properties
```

```
./node_modules/@sentry/cli/bin/sentry-cli react-native appcenter APP_NAME PLATFORM ./build/CodePush --deployment DEPLOYMENT_NAME --release-name RELEASE_NAME --dist DIST_NAME
```

where,
`APP_NAME` is `${owner_name}/${codepush_app_name}`.

`DEPLOYMENT_NAME` is the name of the deployment you want to deploy the changes under i.e. Staging/Production/etc. defined in your codepush app settings.

`PLATFORM` is the platform you want to deploy the changes for i.e. ios/android.

`RELEASE_NAME` for android is: `${applicationId}@${versionName}+${versionCode}` and for iOS is: `${bundleIdentifier}@${version}+${build}`.
This naming convention is mandatory for `RELEASE_NAME` because otherwise sentry's RELEASE Health feature won't work properly. For more details, look at https://github.com/getsentry/sentry-cli/issues/577#issuecomment-610272845
Also, because, when we build our release/staging app via XCode/Android Studio, Sentry always uses that release name (hardcoded by sentry) to upload our sourcemaps and so as not to make a new release on sentry for each codepushed version, we will put them all under one release name, divided by different distribution names i.e. `DIST_NAME`

`DIST_NAME` is `codepush_${codePushUpdateLabel}` where codePushUpdateLabel is the name of your codepush release eg. v21, v22, etc. You can check this out by going into your codepush app webpage on appcenter website and then `Distribute` -> `CodePush` -> `Select your respective deployment`
codePushUpdateLabel will be at the top of of the list since which is the update you just deployed on codepush. eg. `codepush_v22`

**Comment by jorisw** [comment]
We use `@ourcompany/ourproject` as a package name in our projects. The following code yields the same error as OP gets, but for the `release` key:

```javascript
import * as Sentry from '@sentry/react'
import { name, version } from 'package.json'

const release = `${name}@${version}` // "@ourcompany/ourproject@1.0.0"

Sentry.init({
  dsn: "",
  environment: process.env.NODE_ENV,
  release,
  ...
})
```

In the Node ecosystem, it's common to have package names with `@workspace/` prefixes, and still have `@version` at the end when picking a version to install from the commandline.

**Comment by marandaneto** [comment]
https://docs.sentry.io/platforms/react-native/manual-setup/codepush/
the `dist` should be just the `v18` part, or omit the `dist` and set only the `release`, since the Android and iOS SDK already defaults the `dist` to the build number.
