### ISSUE TITLE
Using Sentry directly in native code

### ISSUE THREAD

**Issue by jacklj** [getsentry/sentry-react-native#813]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

Platform:
- [x]  iOS
- [ ]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.3
`react-native` version: 0.60.5

Are you using Expo?
- [ ]  Yes
- [x]  No

Are you using sentry.io or on-premise?
- [x]  sentry.io (SaaS)
- [ ]  on-premise

---------------------------------

I think it is possible to use Sentry directly from the native code in your react-native project, but this doesn't seem to be mentioned anywhere in the docs.

I'd like to be able to e.g. add breadcrumbs and capture exception, directly in Objective-C code.

I assume that when installing Sentry for react-native, it installs Sentry for Cocoa. 

However, when I try and initialise Sentry in AppDelegate.m, with:
```
@import Sentry;

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [SentrySDK initWithOptions:@{
        @"dsn": @"xxx",
        @"debug": @(YES)
    }];
    return YES;
}
```
Xcode says "Module 'Sentry' not found"

What is the correct way to use react-native Sentry directly from (iOS) native code?

Thanks

**Comment by tapz** [comment]
I would also like to know how to use Sentry directly in Java code when integrated to the React Native SDK. Now I just get this:

```
MainActivity.java:69: error: cannot find symbol
import io.sentry.Sentry;
```

**Comment by brandons** [comment]
@jacklj @tapz Did either of you find a solution for this?

**Comment by tapz** [comment]
In Android/Java, I had to change the import to `import io.sentry.core.Sentry;`

In iOS, I simpy do `import Sentry` and then `SentrySDK.capture(event: sentryEvent)`. 

The initialization with dsn is done in RN code by calling `Sentry.init`.

**Comment by jennmueng** [comment]
Hi everyone, I joined Sentry after this issue was made so I didn't see it until now, sorry!

Yes that is correct. On Android it is `io.sentry.core.Sentry` and on iOS it's either `import Sentry` or `import <Sentry/Sentry.h>`.

You do not call init from native code otherwise it might not work with the React Native SDK, although this does mean that any errors before the JS code calls init will not be caught, and calling the init from the native SDK before calling init would not work.
